# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: linklet_dev
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
